name: Test Newman HTML Report
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run Regression.postman_collection.json -e Regression.Azure.postman_environment.json -r htmlextra --reporter-htmlextra-export ${{ github.workspace }}/TestResults/index.html 

      # Upload report as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: report
          if: always()
          path: ${{ github.workspace }}/TestResults/index.html
          
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          if: always()
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/TestResults/
